on:
  workflow_dispatch:
    inputs:
      openssl_version:
        description: "Version of openssl we'll build."
        type: string
        required: true
      zlib_version:
        description: "Version of zlib we'll build."
        type: string
      github_tag:
        description: "Tag to upload the release to."
        type: string
        required: true

name: OpenSSL

jobs:
  build:
    name: build openssl ${{ matrix.runner }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner:
          - ubicloud-standard-8-ubuntu-2204 # linux-x86_64
          - ubicloud-standard-8-arm-ubuntu-2204 # linux-aarch64
          - macos-13 # macos-x86_64
          - macos-14 # macos-aarch64
    permissions:
      contents: write
    steps:
      - name: Clone scufflecloud/toolchains repo
        uses: actions/checkout@v4

      - name: Install required tools (macos)
        if: ${{ runner.os == 'macOS'}}
        run: brew install git nasm yasm make zstd perl

      - name: Install required tools (linux)
        if: ${{ runner.os == 'Linux'}}
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            wget \
            lsb-release \
            zstd \
            perl \
            make \
            nasm \
            yasm

          curl -L https://apt.llvm.org/llvm.sh | sudo bash -s -- 20

          echo "CC=$(which clang-20)" >> $GITHUB_ENV
          echo "CXX=$(which clang++-20)" >> $GITHUB_ENV
          echo "LD=$(which lld-20)" >> $GITHUB_ENV

      - name: Setup dist dir
        run: |
          mkdir -p dist/{zlib,openssl}
          dist_dir=$(realpath dist)
          echo "DIST_DIR=$dist_dir" >> $GITHUB_ENV


      - name: Build Zlib
        run: |
          ZLIB_VERSION="${{ inputs.zlib_version }}"
          git clone https://github.com/madler/zlib.git -b "${ZLIB_VERSION:-v1.3.1}" --depth 1
          pushd zlib
          ./configure --prefix="${DIST_DIR}/zlib" --static
          make -j$(nproc)
          make install

      - name: Build OpenSSL
        run: |
          OPENSSL_VERSION="${{ inputs.openssl_version }}"
          git clone https://github.com/openssl/openssl.git -b "${OPENSSL_VERSION:-3.3.2}" --depth 1
          pushd openssl
          ./Configure --prefix="${DIST_DIR}/openssl" --with-zlib-include="${DIST_DIR}/zlib/include" --with-zlib-lib="${DIST_DIR}/zlib/lib" -Wl,-rpath,'$$ORIGIN'
          make -j$(nproc)
          make install

      - name: Package
        run: |
          arch="$(uname -m)"
          os="$(uname -s)"
          mkdir artifacts
          cd dist/openssl
          tar -cf - * | zstd --ultra -22 -o "../../artifacts/openssl_${{ inputs.openssl_version }}_${os,,}_${arch,,}.tar.zst"

      - name: Upload toolchain to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: "artifacts/*.tar.zst"
          file_glob: true
          tag: ${{ inputs.github_tag }}
          overwrite: true
